[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true

[profile.default.metadata]
bytecodeHash = "ipfs"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"